version: '1.0.{build}'

image: Visual Studio 2017

branches:
  only:
    - master
    
# set clone depth
clone_depth: 5
    
platform:
  - x64
  
configuration:
  - Debug
  - Release
  
matrix:
  fast_finish: true

install:
    - git submodule update --init --recursive

before_build:
  - cmake -E make_directory build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" ..

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).sln
  
test_script:
  - ctest -VV --output-on-failure -C %CONFIGURATION%

notifications:
  - provider: Email
    to:
      - rokodev@mail.ru
    subject: 'Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_success: true #|false
    on_build_failure: true #|false
    on_build_status_changed: true #|false